apiVersion: v1
kind: Service
metadata:
  name: http-server
  labels:
    app: http-server
  annotations:
    # For AWS: network load balancer preserves client IP
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # For GCP:
    # cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: http-server
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  # Preserve client IP for X-Forwarded-For headers
  externalTrafficPolicy: Local
